### ISSUE TITLE
[Request] Method to change the modal presentation style

### ISSUE THREAD

**Issue by Eric-Liqiafeng** [victorbonnet/flutter_web_browser#41]
Hi, dear author
The navigating behavior of "openWebPage" in the plugin is right_in and right_out. I hope there is a parameter to set, which can be set to pop up (bottom_in and bottom_out)
I was wondering if you could implement a function to change the modal presentation style, example as below, thanks

**iOS**
sfvc.modalPresentationStyle = UIModalPresentationOverFullScreen;
![image](https://user-images.githubusercontent.com/27261737/147426113-023f2deb-7468-4e22-9399-fc9c51356862.png)

**Android**
![image](https://user-images.githubusercontent.com/27261737/147426175-4629cdf6-9fab-45b1-9961-6b12968b866a.png)

**Comment by victorbonnet** [comment]
Hi, 
Thanks to @ABausG, we can now configure the presentation style for iOS. 
This is available in version `0.17.1`.

**Comment by Eric-Liqiafeng** [comment]
Thanks.
