### ISSUE TITLE
Support For SDK 31

### ISSUE THREAD

**Issue by Nikhil27b** [victorbonnet/flutter_web_browser#42]
Please add support for SDK 31 its plugin had a issue with SDK 32

**Comment by lohanbodevan** [comment]
I have the same issue and it seems like there is a PR opened to fix this issue: https://github.com/victorbonnet/flutter_web_browser/pull/43
Perhaps @victorbonnet could take a look. Thanks!

**Comment by victorbonnet** [comment]
The PR has been merged and the new release 0.17.0 should be available.
Thanks
